#!/bin/bash
normpath=$(python -c "from os.path import normpath;import sys;print(normpath(sys.argv[1]))" $1) && 
gpg -o $normpath.tar --decrypt $normpath &&
rm $normpath &&
tar -xf $normpath.tar &&
rm $normpath.tar